version: "3"

services:
  babelfishpg-ubuntu-focal:
    container_name: babelfishpg-ubuntu-focal
    build:
      context: .
      dockerfile: Dockerfile.ubuntu-focal
      args:
        buildno: 1
        MAX_JOBS: 4
        RELEASE: BABEL_1_1_0__PG_13_5
    image: babelfishpg:ubuntu.focal
    ports:
      - 1433:1433
      - 5432:15432
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - BABELFISH_USER=jdbc_user
      - BABELFISH_PASS=12345678
      - BABELFISH_DB=jdbc_testdb
      - BABELFISH_MIGRATION_MODE=multi-db
      - POSTGRES_HOST_AUTH_METHOD=trust
      #- POSTGRES_INITDB_ARGS=" -E=UTF8 "
    volumes:
      - ./postgres/entrypoint:/docker-entrypoint-initdb.d/
    networks:
      - babelfish

  jdbctests:
    container_name: jdbctests
    image: maven
    networks:
      - babelfish
    volumes:
      - ./BABEL_1_1_0__PG_13_5.zip:/opt/BABEL_1_1_0__PG_13_5.zip
    command: >
      bash -c "DEBIAN_FRONTEND=interactive microdnf install unzip 
      && unzip -d /opt/babelfishpg /opt/BABEL_1_1_0__PG_13_5.zip 
      && cd /opt/babelfishpg/contrib/test/JDBC/ 
      && sed -i 's/URL = localhost/URL = babelfishpg-ubuntu-focal/' src/main/resources/config.txt && mvn test"
      
networks:
  babelfish:
      