version: "3"

services:
  babelfishpg-ubuntu-focal:
    container_name: babelfishpg-ubuntu-focal
    build:
      context: .
      dockerfile: babelfishpg/ubuntu/focal/Dockerfile
      args:
        buildno: 1
        MAX_JOBS: 4
        BABELTAG: BABEL_4_1_0__PG_16_2
    image: babelfishpg:4.1.0-ubuntu-focal
    ports:
      - 1433:1433
      - 5432:15432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - BABELFISH_USER=bbf
      - BABELFISH_PASS=password
      - BABELFISH_DB=bbf
      - BABELFISH_MIGRATION_MODE=multi-db
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - babelfish

networks:
  babelfish:
      