version: "3"

services:
  babelfishpg-ubuntu-focal:
    container_name: babelfishpg-ubuntu-focal
    build:
      context: .
      dockerfile: Dockerfile.ubuntu-focal
      args:
        buildno: 1
        MAX_JOBS: 4
        RELEASE: BABEL_1_0_0__PG_13_4
    image: babelfishpg:ubuntu.focal
    ports:
      - 1433:1433
      - 5432:15432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - BABELFISH_USER=bbf
      - BABELFISH_PASS=password
      - BABELFISH_DB=bbf
      - BABELFISH_MIGRATION_MODE=multi-db
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - babelfish

  jdbctests:
    container_name: jdbctests
    image: maven
    networks:
      - babelfish
    volumes:
      - ./BABEL_1_0_0__PG_13_4.zip:/opt/BABEL_1_0_0__PG_13_4.zip
    command: >
      bash -c "microdnf install unzip 
        && unzip -d /opt/babelfishpg /opt/BABEL_1_0_0__PG_13_4.zip 
        && cd /opt/babelfishpg/contrib/test/JDBC/ 
        && mvn test"
      
networks:
  babelfish:
      